openapi: 3.1.0
info:
  version: 1.0.0
  title: API Documentation
  description: This is a sample API documentation using Swagger
  termsOfService: http://example.com/terms/
  contact:
    name: API Support
    email: support@example.com
    url: http://example.com/support
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
host: api.example.com
basePath: /v1
schemes:
  - https
  - http
paths:
  /vendors:
    get:
      summary: Get all vendors
      description: Returns a list of all vendors.
      responses:
        200:
          description: A list of vendors
          schema:
            type: array
            items:
              ref: '#/definitions/Vendor'
  /vendors/{id}:
    get:
      summary: Get a vendor by ID
      parameters:
        - name: id
          in: path
          required: true
          type: string
          description: ID of the vendors to retrieve
      responses:
        200:
          description: vendors details
          schema:
            ref: '#/definitions/Vendor'
        404:
          description: User not found
components:
  schemas:
    Vendor:
      type: object
      properties:
        id:
          type: string
          example: 12345
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
      required:
        - id
        - firstName
        - lastName
