swagger: '2.0'
info:
  version: '1.0.0'
  title: 'API Documentation'
  description: 'This is a sample API documentation using Swagger'
  termsOfService: 'http://example.com/terms/'
  contact:
    name: 'API Support'
    email: 'support@example.com'
    url: 'http://example.com/support'
  license:
    name: 'MIT'
    url: 'https://opensource.org/licenses/MIT'
host: 'api.example.com'
basePath: '/v1'
schemes:
  - 'https'
  - 'http'
paths:
  /users:
    get:
      summary: 'Get all users'
      description: 'Returns a list of all users.'
      responses:
        '200':
          description: 'A list of users'
          schema:
            type: 'array'
            items:
              ref: '#/definitions/User'
  /users/{id}:
    get:
      summary: 'Get a user by ID'
      parameters:
        - name: 'id'
          in: 'path'
          required: true
          type: 'string'
          description: 'ID of the user to retrieve'
      responses:
        '200':
          description: 'User details'
          schema:
            ref: '#/definitions/User'
        '404':
          description: 'User not found'
definitions:
  User:
    type: 'object'
    properties:
      id:
        type: 'string'
        example: '12345'
      name:
        type: 'string'
        example: 'John Doe'
      email:
        type: 'string'
        example: 'john.doe@example.com'
    required:
      - 'id'
      - 'name'
      - 'email'
